### PR TITLE
Revert "prefer local environment to docker, refactor Makefiles"

### PR DESCRIPTION
**Pull request by asirota**
Reverts aspirepress/AspireSync#25

### CODE REVIEW

**Comment by chuckadams** [comment]
# ❓ 

 Why was the PR reverted?  A description would have helped...

**Comment by asirota** [comment]
Sorry? It's been merged.

**Comment by chuckadams** [comment]
Yes, #25 was merged, then this one was merged, which reverts #25.  Why was it reverted?

**Comment by asirota** [comment]
I accidentally reverted #25. Then I recreated 27 and merged it. Do things look ok?

**Comment by asirota** [comment]
I think I made a mistake and reverted 25 by accident. Can you make a new PR which will recreate the original pr #25.  Sorry about that!

**Pull request merged**
